### ISSUE TITLE
crypto no longer works

### ISSUE THREAD

**Issue by pdparchitect** [browserify/browserify#1720]
It looks like something broke crypto with changes pushed today. Did not investigate where the change came from so I am reporting it here.

To reproduce:

```javascript
var crypto = require('crypto')
```

This will produce the following error:

```
index.js:3 Uncaught TypeError: Cannot read property 'toString' of undefined
    at Object.require.270.crypto (index.js:3)
    at s (_prelude.js:1)
    at _prelude.js:1
    at Object.require.164.browserify-cipher (index.js:12)
    at s (_prelude.js:1)
    at _prelude.js:1
    at Object.require.1.../../src/example (index.js:7)
    at s (_prelude.js:1)
    at e (_prelude.js:1)
    at _prelude.js:1
```

where:

```javascript
crypto.pbkdf2Sync.toString()
```

will is called on undefined object, i.e. crypto.pbkdf2Sync is not defined.

Again, this regression is relatively new. Perhaps due to a change from today.

**Comment by vivek0tiwari** [comment]
Facing the same issue in `crypto.pbkdf2Sync.toString()`

**Comment by JustinBeaudry** [comment]
There are no changes that were pushed today. Must be a dependency that pushed changes that is breaking this. `crypto-browserify` was my first thought, but that doesn't seem to have been updated either https://github.com/crypto-browserify/crypto-browserify. Maybe it's a dependency of `crypto-browserify`?

**Comment by JustinBeaudry** [comment]
Likely might be https://github.com/crypto-browserify/createHash/releasesm, which updated 6 hours ago with a new patch version.

**Comment by JustinBeaudry** [comment]
Looking at https://github.com/crypto-browserify/createHash as a likely candidate for the regression.

**Comment by vivek0tiwari** [comment]
Issue is fixed from new version of pbkdf2(3.0.12)

**Comment by JustinBeaudry** [comment]
I was just going down that rabbit hole, thanks for the reply!

**Comment by JustinBeaudry** [comment]
@vivek0tiwari Confirmed the issue is now resolved. @pdparchitect try re`npm i`ing browserify.

**Comment by pdparchitect** [comment]
Yes fixed!

**Comment by cbartondock** [comment]
I'm still seeing this when I do `import crypto from 'crypto'`.

**Comment by lvcmenezes** [comment]
also still see the same error here..

**Comment by fryck** [comment]
Same for me...
